### ISSUE TITLE
Unable to play/stop game if you unplug joystick 1 and have joystick 2

### ISSUE THREAD

**Issue by nadenislamarre** [recalbox/recalbox-configgen#15]
Have 2 joysticks.
Configure :
JOY1 => P1
JOY2 => P2

Unplug JOY1.

P1 is marked as DEFAULT
P2 is marked as JOY2.

This is ok.
Start a game.

It calls :
emulatorlauncher.pyc -p2index 0 -p2guid 03000000a30600000cff000010010000 -p2name "Saitek PLC Cyborg Force Rumble Pad" -p2devicepath /dev/input/event0  -system snes -rom /recalbox/share/roms/snes/DonkeyKongClassic\ \(Shiru\).smc -emulator default -core default

An it seems that in case there is no p1, no other player switch to p1.
Thus, you cannot quit or play.
More generally, it there is a whole, for example :
p1 p4 => replace p4 by p2...

**Comment by digitalLumberjack** [comment]
I think it's normal as you forced the only available joystick on P2.

**Comment by nadenislamarre** [comment]
and dont you think in case thrz is no p1 it shoould be changed ?
it happends regularly to me. but i want to set because when plug i prefer
this one
Le 2 janv. 2016 15:05, "digitalLumberjack" <notifications@github.com> a
écrit :
